version: "3.5"
services:
  nodejs:
    build: .
    container_name: "mqtt-blinds"
    volumes:
      - ./config:/usr/src/app/config
    networks:
      - app
  bash:
    build: .
    entrypoint: /bin/sh
networks:
  app:
