version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.12
    volumes:
      - ./data:/mosquitto/data
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log
    ports:
      - "1883:1883"
    environment:
      - TZ=Australia/Perth
    restart: always
    privileged: true
    user: 1000:1000
